### ISSUE TITLE
Have any way copyright remove from movies clips for Facebook 

### ISSUE THREAD

**Issue by Tipsandtricksbd01** [vasani-arpit/Youtube-remove-copyright#13]
Hello sir, 
I want to how to remove copyright segment or copyright from movie for Facebook.

I see many Facebook page they upload movie clips without copyright strike. How it's possible.
If you possible to share please send me one mail.

Best regards
Mizanur Rahman
raw.mizanur@gmail.com

**Comment by vasani-arpit** [comment]
Sorry don't know much about that.
